In [1]:
import statsmodels.api as sm
from scipy import stats

In [2]:
import pandas as pd
pd.options.display.float_format = '{:,.4f}'.format
pd.options.display.max_rows = 100
pd.options.display.max_columns = 40
import numpy as np
import os,random, math
from tqdm import tqdm
from copy import deepcopy
from collections import Counter

# Visualization
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
from matplotlib import font_manager, rc
plt.rcParams['font.family'] = 'NanumGothic'
import platform
if platform.system() == 'Windows':
    font_name = font_manager.FontProperties(fname="c:/Windows/Fonts/malgun.ttf").get_name()
    rc('font', family=font_name)
else:    
    rc('font', family='AppleGothic')

matplotlib.rcParams['axes.unicode_minus'] = False

# from dataprep.eda import plot, plot_correlation, plot_missing

# Warnings
import warnings
warnings.filterwarnings('always')
warnings.filterwarnings('ignore')

In [3]:
import os
path = os.path.dirname(os.getcwd())
path = os.path.join(path, "ProcessedData")
train = pd.read_csv(os.path.join(path,"merged_train.csv"))
test = pd.read_csv(os.path.join(path,"merged_test.csv"))

In [10]:
train[train.단지코드.isin(["C1176"])]

,단지코드,총세대수,임대건물구분,지역,공급유형,전용면적,전용면적별세대수,공가수,자격유형,임대보증금,임대료,지하철역,버스정류장,단지내주차면수,등록차량수,단지명,도로명주소,연면적,위도,경도,subway_name,subway_dist,환승역 수,총인구수,세대당_인구,남/여비율,남/여_0~19세,남/여_20~39세,남/여_40~69세,남/여_70세이상,0~19세_비율,20~39세_비율,40~69세_비율,70세이상_비율
2294,C1176,1486,아파트,충청북도,국민임대,26.5800,199,55.0000,H,"8,563,000.0000","116,950.0000",0.0000,3.0000,"1,493.0000",619.0000,청주동남A-1블록(국민임대),충청북도 청주시 상당구 호미로 137,"7,263.4885",127.5193,36.6212,대전역,0.3012,1,"47,196.0000",2.4850,0.9850,2.0854,1.0781,0.9611,0.6261,0.2164,0.2836,0.4433,0.0567
2295,C1176,1486,아파트,충청북도,국민임대,26.5800,149,55.0000,H,"8,563,000.0000","116,950.0000",0.0000,3.0000,"1,493.0000",619.0000,청주동남A-1블록(국민임대),충청북도 청주시 상당구 호미로 137,"7,263.4885",127.5193,36.6212,대전역,0.3012,1,"47,196.0000",2.4850,0.9850,2.0854,1.0781,0.9611,0.6261,0.2164,0.2836,0.4433,0.0567
2296,C1176,1486,아파트,충청북도,국민임대,37.7800,313,55.0000,H,"18,140,000.0000","179,270.0000",0.0000,3.0000,"1,493.0000",619.0000,청주동남A-1블록(국민임대),충청북도 청주시 상당구 호미로 137,"7,263.4885",127.5193,36.6212,대전역,0.3012,1,"47,196.0000",2.4850,0.9850,2.0854,1.0781,0.9611,0.6261,0.2164,0.2836,0.4433,0.0567
2297,C1176,1486,아파트,충청북도,국민임대,37.7800,26,55.0000,H,"18,140,000.0000","179,270.0000",0.0000,3.0000,"1,493.0000",619.0000,청주동남A-1블록(국민임대),충청북도 청주시 상당구 호미로 137,"7,263.4885",127.5193,36.6212,대전역,0.3012,1,"47,196.0000",2.4850,0.9850,2.0854,1.0781,0.9611,0.6261,0.2164,0.2836,0.4433,0.0567
2298,C1176,1486,아파트,충청북도,국민임대,37.7800,179,55.0000,H,"18,140,000.0000","179,270.0000",0.0000,3.0000,"1,493.0000",619.0000,청주동남A-1블록(국민임대),충청북도 청주시 상당구 호미로 137,"7,263.4885",127.5193,36.6212,대전역,0.3012,1,"47,196.0000",2.4850,0.9850,2.0854,1.0781,0.9611,0.6261,0.2164,0.2836,0.4433,0.0567
2299,C1176,1486,아파트,충청북도,국민임대,37.7800,20,55.0000,H,"18,140,000.0000","179,270.0000",0.0000,3.0000,"1,493.0000",619.0000,청주동남A-1블록(국민임대),충청북도 청주시 상당구 호미로 137,"7,263.4885",127.5193,36.6212,대전역,0.3012,1,"47,196.0000",2.4850,0.9850,2.0854,1.0781,0.9611,0.6261,0.2164,0.2836,0.4433,0.0567
2300,C1176,1486,아파트,충청북도,국민임대,46.8300,250,55.0000,H,"29,080,000.0000","239,910.0000",0.0000,3.0000,"1,493.0000",619.0000,청주동남A-1블록(국민임대),충청북도 청주시 상당구 호미로 137,"7,263.4885",127.5193,36.6212,대전역,0.3012,1,"47,196.0000",2.4850,0.9850,2.0854,1.0781,0.9611,0.6261,0.2164,0.2836,0.4433,0.0567
2301,C1176,1486,아파트,충청북도,국민임대,46.9700,350,55.0000,H,"29,080,000.0000","239,910.0000",0.0000,3.0000,"1,493.0000",619.0000,청주동남A-1블록(국민임대),충청북도 청주시 상당구 호미로 137,"7,263.4885",127.5193,36.6212,대전역,0.3012,1,"47,196.0000",2.4850,0.9850,2.0854,1.0781,0.9611,0.6261,0.2164,0.2836,0.4433,0.0567

In [12]:
train[train.단지코드.isin(["C1363"])]

,단지코드,총세대수,임대건물구분,지역,공급유형,전용면적,전용면적별세대수,공가수,자격유형,임대보증금,임대료,지하철역,버스정류장,단지내주차면수,등록차량수,단지명,도로명주소,연면적,위도,경도,subway_name,subway_dist,환승역 수,총인구수,세대당_인구,남/여비율,남/여_0~19세,남/여_20~39세,남/여_40~69세,남/여_70세이상,0~19세_비율,20~39세_비율,40~69세_비율,70세이상_비율
1904,C1363,2568,아파트,경기도,국민임대,26.8500,150,11.0000,H,"17,021,000.0000","158,060.0000",0.0000,6.0000,"1,798.0000","2,550.0000",위례35단지 아파트,경기도 성남시 수정구 위례광장로 311,"7,689.1800",127.1449,37.4726,산성역,0.0165,1,"45,750.0000",2.5400,0.9600,2.1171,0.9421,0.9833,0.7515,0.1986,0.2810,0.4524,0.0680
1905,C1363,2568,아파트,경기도,국민임대,26.8500,88,11.0000,H,"17,021,000.0000","158,060.0000",0.0000,6.0000,"1,798.0000","2,550.0000",위례35단지 아파트,경기도 성남시 수정구 위례광장로 311,"7,689.1800",127.1449,37.4726,산성역,0.0165,1,"45,750.0000",2.5400,0.9600,2.1171,0.9421,0.9833,0.7515,0.1986,0.2810,0.4524,0.0680
1906,C1363,2568,아파트,경기도,국민임대,29.9200,90,11.0000,H,"19,451,000.0000","175,260.0000",0.0000,6.0000,"1,798.0000","2,550.0000",위례35단지 아파트,경기도 성남시 수정구 위례광장로 311,"7,689.1800",127.1449,37.4726,산성역,0.0165,1,"45,750.0000",2.5400,0.9600,2.1171,0.9421,0.9833,0.7515,0.1986,0.2810,0.4524,0.0680
1907,C1363,2568,아파트,경기도,국민임대,29.9200,72,11.0000,H,"19,451,000.0000","175,260.0000",0.0000,6.0000,"1,798.0000","2,550.0000",위례35단지 아파트,경기도 성남시 수정구 위례광장로 311,"7,689.1800",127.1449,37.4726,산성역,0.0165,1,"45,750.0000",2.5400,0.9600,2.1171,0.9421,0.9833,0.7515,0.1986,0.2810,0.4524,0.0680
1908,C1363,2568,아파트,경기도,국민임대,29.9200,340,11.0000,H,"19,451,000.0000","175,260.0000",0.0000,6.0000,"1,798.0000","2,550.0000",위례35단지 아파트,경기도 성남시 수정구 위례광장로 311,"7,689.1800",127.1449,37.4726,산성역,0.0165,1,"45,750.0000",2.5400,0.9600,2.1171,0.9421,0.9833,0.7515,0.1986,0.2810,0.4524,0.0680
1909,C1363,2568,아파트,경기도,국민임대,36.9600,375,11.0000,H,"23,892,000.0000","224,730.0000",0.0000,6.0000,"1,798.0000","2,550.0000",위례35단지 아파트,경기도 성남시 수정구 위례광장로 311,"7,689.1800",127.1449,37.4726,산성역,0.0165,1,"45,750.0000",2.5400,0.9600,2.1171,0.9421,0.9833,0.7515,0.1986,0.2810,0.4524,0.0680
1910,C1363,2568,아파트,경기도,국민임대,36.9600,144,11.0000,H,"23,892,000.0000","224,730.0000",0.0000,6.0000,"1,798.0000","2,550.0000",위례35단지 아파트,경기도 성남시 수정구 위례광장로 311,"7,689.1800",127.1449,37.4726,산성역,0.0165,1,"45,750.0000",2.5400,0.9600,2.1171,0.9421,0.9833,0.7515,0.1986,0.2810,0.4524,0.0680
1911,C1363,2568,아파트,경기도,국민임대,36.9600,45,11.0000,H,"23,892,000.0000","224,730.0000",0.0000,6.0000,"1,798.0000","2,550.0000",위례35단지 아파트,경기도 성남시 수정구 위례광장로 311,"7,689.1800",127.1449,37.4726,산성역,0.0165,1,"45,750.0000",2.5400,0.9600,2.1171,0.9421,0.9833,0.7515,0.1986,0.2810,0.4524,0.0680
1912,C1363,2568,아파트,경기도,국민임대,46.4900,58,11.0000,H,"51,763,000.0000","287,090.0000",0.0000,6.0000,"1,798.0000","2,550.0000",위례35단지 아파트,경기도 성남시 수정구 위례광장로 311,"7,689.1800",127.1449,37.4726,산성역,0.0165,1,"45,750.0000",2.5400,0.9600,2.1171,0.9421,0.9833,0.7515,0.1986,0.2810,0.4524,0.0680
1913,C1363,2568,아파트,경기도,국민임대,46.4900,141,11.0000,H,"51,763,000.0000","287,090.0000",0.0000,6.0000,"1,798.0000","2,550.0000",위례35단지 아파트,경기도 성남시 수정구 위례광장로 311,"7,689.1800",127.1449,37.4726,산성역,0.0165,1,"45,750.0000",2.5400,0.9600,2.1171,0.9421,0.9833,0.7515,0.1986,0.2810,0.4524,0.0680
1914,C1363,2568,아파트,경기도,국민임대,46.7700,515,11.0000,H,"51,763,000.0000","287,090.0000",0.0000,6.0000,"1,798.0000","2,550.0000",위례35단지 아파트,경기도 성남시 수정구 위례광장로 311,"7,689.1800",127.1449,37.4726,산성역,0.0165,1,"45,750.0000",2.5400,0.9600,2.1171,0.9421,0.9833,0.7515,0.1986,0.2810,0.4524,0.0680
1915,C1363,2568,아파트,경기도,영구임대,21.9500,86,11.0000,I,"10,718,000.0000","71,930.0000",0.0000,6.0000,"1,798.0000","2,550.0000",위례35단지 아파트,경기도 성남시 수정구 위례광장로 311,"7,689.1800",127.1449,37.4726,산성역,0.0165,1,"45,750.0000",2.5400,0.9600,2.1171,0.9421,0.9833,0.7515,0.1986,0.2810,0.4524,0.0680
1916,C1363,2568,아파트,경기도,영구임대,26.8500,300,11.0000,I,"12,881,000.0000","87,840.0000",0.0000,6.0000,"1,798.0000","2,550.0000",위례35단지 아파트,경기도 성남시 수정구 위례광장로 311,"7,689.1800",127.1449,37.4726,산성역,0.0165,1,"45,750.0000",2.5400,0.9600,2.1171,0.9421,0.9833,0.7515,0.1986,0.2810,0.4524,0.0680
1917,C1363,2568,아파트,경기도,영구임대,26.8500,164,11.0000,I,"12,881,000.0000","87,840.0000",0.0000,6.0000,"1,798.0000","2,550.0000",위례35단지 아파트,경기도 성남시 수정구 위례광장로 311,"7,689.1800",127.1449,37.4726,산성역,0.0165,1,"45,750.0000",2.5400,0.9600,2.1171,0.9421,0.9833,0.7515,0.1986,0.2810,0.4524,0.0680

In [7]:
train.describe()

,총세대수,전용면적,전용면적별세대수,공가수,임대보증금,임대료,지하철역,버스정류장,단지내주차면수,등록차량수,연면적,위도,경도,subway_dist,환승역 수,총인구수,세대당_인구,남/여비율,남/여_0~19세,남/여_20~39세,남/여_40~69세,남/여_70세이상,0~19세_비율,20~39세_비율,40~69세_비율,70세이상_비율
count,"2,896.0000","2,896.0000","2,896.0000","2,896.0000","2,896.0000","2,896.0000","2,896.0000","2,896.0000","2,896.0000","2,896.0000","2,896.0000","2,896.0000","2,896.0000","2,896.0000","2,896.0000","2,896.0000","2,896.0000","2,896.0000","2,896.0000","2,896.0000","2,896.0000","2,896.0000","2,896.0000","2,896.0000","2,896.0000","2,896.0000"
mean,889.8142,44.5590,102.8225,12.9347,"23,810,141.5722","715,145.7491",0.1992,3.7051,598.7666,558.3160,"3,726.6825",127.7250,36.1738,0.2302,1.0704,"31,671.4539",2.2803,0.9930,1.9704,1.1156,0.9978,0.6799,0.1848,0.2492,0.4602,0.1059
std,516.4258,32.0006,132.9886,10.6653,"23,575,659.1410","3,158,749.5339",0.4414,2.6647,396.6776,437.0157,"4,568.9573",0.8549,1.1058,0.3565,0.2559,"21,788.0188",0.2702,0.0583,0.2561,0.1406,0.0818,0.0656,0.0509,0.0443,0.0358,0.0508
min,26.0000,12.6200,1.0000,0.0000,"25,600.0000",0.0000,0.0000,0.0000,13.0000,13.0000,5.6880,126.2662,33.2498,0.0006,1.0000,"1,706.0000",1.5900,0.8700,1.2617,0.8727,0.8590,0.4955,0.0594,0.0972,0.3562,0.0232
25%,514.0000,32.1000,14.7500,4.0000,"10,923,000.0000","111,470.0000",0.0000,2.0000,277.0000,209.0000,280.6700,127.0780,35.2091,0.0132,1.0000,"15,466.0000",2.0700,0.9550,1.7857,1.0050,0.9454,0.6312,0.1464,0.2149,0.4373,0.0680
50%,777.0000,39.9050,60.0000,11.0000,"18,217,000.0000","164,480.0000",0.0000,3.0000,507.0000,481.0000,"2,847.0600",127.4467,36.2846,0.0429,1.0000,"25,797.0000",2.2800,0.9800,1.9318,1.1044,0.9833,0.6762,0.1928,0.2517,0.4578,0.0952
75%,"1,106.0000",51.2925,143.2500,20.0000,"28,842,500.0000","259,660.0000",0.0000,4.0000,823.0000,763.0000,"5,862.8600",128.5579,37.2985,0.3516,1.0000,"41,315.0000",2.5100,1.0100,2.1073,1.2004,1.0297,0.7288,0.2211,0.2807,0.4886,0.1440
max,"2,568.0000",583.4000,"1,865.0000",55.0000,"395,801,928.4000","81,594,000.0000",3.0000,20.0000,"1,798.0000","2,550.0000","53,027.3008",129.3959,38.2023,1.8900,2.0000,"120,892.0000",2.8933,1.4500,2.9983,2.2382,1.6373,0.8476,0.2990,0.3980,0.5483,0.3723

In [11]:
train[train.단지코드.isin(["C2612"])]

,단지코드,총세대수,임대건물구분,지역,공급유형,전용면적,전용면적별세대수,공가수,자격유형,임대보증금,임대료,지하철역,버스정류장,단지내주차면수,등록차량수,단지명,도로명주소,연면적,위도,경도,subway_name,subway_dist,환승역 수,총인구수,세대당_인구,남/여비율,남/여_0~19세,남/여_20~39세,남/여_40~69세,남/여_70세이상,0~19세_비율,20~39세_비율,40~69세_비율,70세이상_비율
1856,C2612,1684,아파트,세종특별자치시,국민임대,29.7100,628,27.0000,A,"9,800,000.0000","154,000.0000",0.0000,2.0000,"1,689.0000","1,832.0000",가재마을 1단지,세종특별자치시 도움1로 145,134.4800,127.2426,36.5010,반석역,0.1304,1,"29,394.0000",2.7300,0.9500,2.0407,0.9031,0.9573,0.7256,0.2986,0.2660,0.3962,0.0392
1857,C2612,1684,아파트,세종특별자치시,국민임대,29.7100,54,27.0000,A,"9,800,000.0000","154,000.0000",0.0000,2.0000,"1,689.0000","1,832.0000",가재마을 1단지,세종특별자치시 도움1로 145,134.4800,127.2426,36.5010,반석역,0.1304,1,"29,394.0000",2.7300,0.9500,2.0407,0.9031,0.9573,0.7256,0.2986,0.2660,0.3962,0.0392
1858,C2612,1684,아파트,세종특별자치시,국민임대,36.6100,620,27.0000,A,"12,800,000.0000","197,000.0000",0.0000,2.0000,"1,689.0000","1,832.0000",가재마을 1단지,세종특별자치시 도움1로 145,134.4800,127.2426,36.5010,반석역,0.1304,1,"29,394.0000",2.7300,0.9500,2.0407,0.9031,0.9573,0.7256,0.2986,0.2660,0.3962,0.0392
1859,C2612,1684,아파트,세종특별자치시,국민임대,46.4100,382,27.0000,A,"27,500,000.0000","257,000.0000",0.0000,2.0000,"1,689.0000","1,832.0000",가재마을 1단지,세종특별자치시 도움1로 145,134.4800,127.2426,36.5010,반석역,0.1304,1,"29,394.0000",2.7300,0.9500,2.0407,0.9031,0.9573,0.7256,0.2986,0.2660,0.3962,0.0392